<?php
namespace bingher\transmit;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Type\TType;

class Transmit_invoke_args
{
    public static $isValidate = false;

    public static $_TSPEC = array(
        1 => array(
            'var'        => 'func',
            'isRequired' => true,
            'type'       => TType::STRING,
        ),
        2 => array(
            'var'        => 'data',
            'isRequired' => false,
            'type'       => TType::STRING,
        ),
    );

    /**
     * @var string
     */
    public $func = null;
    /**
     * @var string
     */
    public $data = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['func'])) {
                $this->func = $vals['func'];
            }
            if (isset($vals['data'])) {
                $this->data = $vals['data'];
            }
        }
    }

    public function getName()
    {
        return 'Transmit_invoke_args';
    }

    public function read($input)
    {
        $xfer  = 0;
        $fname = null;
        $ftype = 0;
        $fid   = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->func);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->data);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('Transmit_invoke_args');
        if ($this->func !== null) {
            $xfer += $output->writeFieldBegin('func', TType::STRING, 1);
            $xfer += $output->writeString($this->func);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->data !== null) {
            $xfer += $output->writeFieldBegin('data', TType::STRING, 2);
            $xfer += $output->writeString($this->data);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
